---
# tasks file for vector-role
  - block:
      - name: Get vector distrib
        ansible.builtin.get_url:
          url: "https://packages.timber.io/vector/0.32.1/vector-{{ vector_version }}.x86_64.rpm"
          dest: "./vector-{{ vector_version }}.rpm"
  - name: Install vector package
    become: true
    ansible.builtin.yum:
      name:
        - vector-{{ vector_version }}.rpm
    notify: Start vector service
  - name: Flush handlers
    ansible.builtin.meta: flush_handlers
  - name: Create configuration using jinja2
    become: true
    ansible.builtin.template:
      src: templates/vector_cfg.j2
      dest: /etc/vector/vector.toml